### ISSUE TITLE
Should include a limit of reports on a node generated by json_file

### ISSUE THREAD

**Issue by evaryont** [chef-cookbooks/chef_handler#24]
One of my nodes has a small disk, and I got an alert about the disk almost filling up. While investigating larger sources, I noticed that the directory `/var/chef/reports` isn't cleaned up.

For now, I'm using the following to delete all the reports older than 7 days:

``` ruby
one_week_ago = Time.now - 60*60*24*7
# There are a bunch of old reports generated by Chef's JSON file handler. Clean
# up all of them older than 1 week
Dir['/var/chef/reports/*.json'].each do |path|
  path_ctime = ::File.stat(path).ctime
  file path do
    action :delete
    backup false
    only_if { path_ctime < one_week_ago }
  end

  # break early so we don't call stat() on all the recent files, small
  # optimization
  break if path_ctime > one_week_ago
end
```

**Comment by lamont-granquist** [comment]
that looks like example code that probably shouldn't be used in production.  i'd accept either pull requests to fix or pull requests to remove it and/or just clarify the documentation.  there appears to be no interest in maintaining it -- please open a PR to fix it if you disagree.
