### ISSUE TITLE
"current" symlink for chef-run-report

### ISSUE THREAD

**Issue by jcderose** [chef-cookbooks/chef_handler#32]
This is an enhancement request: I'd love it if chef_handler created a chef-run-report-current.json file which symlinked to the most recent chef-run-report-(timestamp).json file. It's far easier for me to tell my serverspec/spec_helper.rb file to parse a static filename (e.g. "/var/chef/reports/chef-run-report-current.json") rather than a dynamic filename named with a timestamp that may be slightly different than the current time when spec_helper.rb runs.

**Comment by coderanger** [comment]
That seems like something unrelated to `chef_handler`. Can you say why you think this is related?

**Comment by jcderose** [comment]
@coderanger because chef_handler::json_file creates said chef-run-report-(timestamp).json file?

**Comment by coderanger** [comment]
@jcderose Yeah but `Chef::Handler::JsonFile` lives in Chef itself, not this cookbook. Though maybe we should reconsider that :)

**Comment by jcderose** [comment]
Ah, okay. I misunderstood the purpose of chef_handler::json_file.

**Comment by jcderose** [comment]
For the record: Chef's documentation says the json_file handler is available through the `chef_handler` cookbook, not through Chef itself. That's why I was under the impression I needed the `chef_handler` cookbook to implement `Chef::Handler::JsonFile`.

https://docs.chef.io/handlers.html#json-file-handler
