### ISSUE TITLE
Chef Access Denied to /var/chef/reports

### ISSUE THREAD

**Issue by jcderose** [chef-cookbooks/chef_handler#33]
I want my serverspec/spec_helper.rb file to read the /var/chef/reports/chef-run-report-(timestamp).json files saved by chef_handler. Unfortunately, the /var/chef/reports directory is locked down so only root can read it. Is there an easier way for Chef to access the chef-run-report files in this directory?

**Comment by coderanger** [comment]
Again, this isn't related to this cookbook. The JsonFile handler is part of Chef, not this cookbook.

**Comment by jcderose** [comment]
Chef's documentation points to the chef_handler cookbook to implement the JSONFile handler functionality. 

I guess my question is: is there any possibility of adding logic to the chef_handler::json_file recipe so that Chef can read the /var/chef/reports/ directory?

**Comment by coderanger** [comment]
No, that code would belong in the handler itself, just like I said last time. I realize the docs are wrong, but that doesn't change where the code lives :)

**Comment by jcderose** [comment]
So I should open an issue against chef-cookbooks/chef-client ?

**Comment by coderanger** [comment]
No, the code is actually inside Chef itself. You could submit a patch to add some `chmod` calls near https://github.com/chef/chef/blob/master/lib/chef/handler/json_file.rb#L43. I would say the current behavior is correct though, the reports can contain sensitive information so they should be root/root/400. If you are running Serverspec inside Test Kitchen, it should already be running as root.

**Comment by lamont-granquist** [comment]
yeah the json_file handler is an example handler, you should probably fork it an implement something that works better for you.  pull requests would be accepted to make it better (either in core or here) or to fix the documentation, but nothing will be done with open issues against it.
