### ISSUE TITLE
chef handler 1.2.0 breaks backwards compatibility without a major version change

### ISSUE THREAD

**Issue by miketheman** [chef-cookbooks/chef_handler#34]
When breaking support on a given version of Chef, it is a Good idea to perform a major version bump, to signal to others that this has changed.

We just spent the better part of 2 hours trying to debug this.

This is covered in the CVP under "Miscellaneous Major Version Changes" - it's a good set of guidelines.

**Comment by tas50** [comment]
This absolutely should have been a 2.0 release.  In other cookbooks as we've removed support for either Chef 10 or 11 bumped a major version.  We're not perfect with Semver, but we're making an attempt to allow for predictable tagging by customers.  Sorry about this one.

**Comment by miketheman** [comment]
Thanks for the swift response @tas50 .

Any chance of yanking 1.2.0 and publishing 2.0.0?

**Comment by coderanger** [comment]
It's been 6 months, I would say that would do more harm than good at this point.

**Comment by tas50** [comment]
Agreeing with @coderanger here. The ship already sailed here unfortunately. We can only work to not do this again.

**Comment by miketheman** [comment]
I understand your decisions, and support them, despite being hit directly. :smile: 
Next time!
