### ISSUE TITLE
Audit mode events are not included in report 

### ISSUE THREAD

**Issue by amirbarkal** [chef-cookbooks/chef_handler#36]
When using [audit-cis](https://supermarket.chef.io/cookbooks/audit-cis) cookbook with audit_mode enabled, audit messages are not included in json report.

Is there a way to include audit events in the json report?
Thanks

**Comment by lamont-granquist** [comment]
reporting and auditing are two separate reporting features inside of chef-client.  you can look at the code for both reporters along with how the json_file reporter is implemented as a handler but short of submitting PRs we will not be maintaining it.
