### ISSUE TITLE
In why-run mode no handlers are loaded -- is this a bug or a feature?

### ISSUE THREAD

**Issue by lamont-granquist** [chef-cookbooks/chef_handler#40]
all the converge_by() blocks mean that those actions are no-op'd in why-run mode.

is that on purpose?

or did someone use converge_by just to get the nice green text in doc mode and not understand what they were doing?

what /should/ the behavior be of handlers in why-run mode?   should it be selectable by the handler?  should handlers themselves simply be responsible for checking Chef::Config[:why_run] and DTRT?

**Comment by bleything** [comment]
I _think_ this is causing why-run mode to fail for me:

```
  * chef_handler[Chef::Handler::Slack] action enable
    - Would disable Chef::Handler::Slack as a start handler
    - Would disable Chef::Handler::Slack as a report handler
    - Would disable Chef::Handler::Slack as a exception handler
    - Would load Chef::Handler::Slack from /var/chef/handlers/slack_handler_webhook.rb
    ================================================================================
    Error executing action `enable` on resource 'chef_handler[Chef::Handler::Slack]'
    ================================================================================
    
    NameError
    ---------
    uninitialized constant Slack
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/chef_handler/libraries/helpers.rb:51:in `const_get'
    /var/chef/cache/cookbooks/chef_handler/libraries/helpers.rb:51:in `get_class'
    /var/chef/cache/cookbooks/chef_handler/providers/default.rb:48:in `block in class_from_file'
    /var/chef/cache/cookbooks/slack_handler/recipes/default.rb:58:in `from_file'
    /var/chef/cache/cookbooks/orcasnet/recipes/default.rb:20:in `from_file'
```

It may be that the Slack handler could be written in a way that would avoid that... I have no idea. I'll open an issue with them, but wanted to provide a concrete example of how the current behaviour in this cookbook might be problematic.

**Comment by bleything** [comment]
Actually... I think my issue is related but deserving of a separate issue. Sorry for the noise.

**Comment by lamont-granquist** [comment]
So, IMO:

- the converge_by's just need to be deleted

- if someone wants to use nicer output formatting they should add lines which cause output formatting to happen (IDK what that would be, someone would need to hunt around the doc formatter and/or the implementation details of converge_by to figure out how to only send out formatted output without also doing the updated_by_last_action and the why-run no-op'ing).

- if someone wants to fix why-run mode then manually checking `Chef::Config[:why_run]` should happen instead of using `converge_by`

**Comment by lamont-granquist** [comment]
actually stronger statement:  handlers should be responsible for checking `Chef::Config[:why_run]` themselves and make sure that they're why-run safe (i.e. particularly that they can no-op themselves if their own chef_gem's haven't been loaded -- that is outside of the scope of this cookbook).
