### ISSUE TITLE
why-run mode broken in 1.4.0

### ISSUE THREAD

**Issue by bleything** [chef-cookbooks/chef_handler#41]
### Cookbook version

v1.4.0
### Chef-client version

v12.10.24
### Platform Details

Ubuntu 14.04 LTS
### Scenario:

I'm trying to use why-run mode and finding that having a `chef_handler` resource somewhere in my run list causes the chef run to fail.
### Steps to Reproduce:

In my specific case, include the [`slack_handler`](https://github.com/rackspace-cookbooks/chef-slack_handler) cookbook in a node's run list and then try to run chef in why-run mode. I can come up with a simpler repro case if necessary.
### Expected Result:

why-run mode to succeed
### Actual Result:

```
  * chef_handler[Chef::Handler::Slack] action enable
    - Would disable Chef::Handler::Slack as a start handler
    - Would disable Chef::Handler::Slack as a report handler
    - Would disable Chef::Handler::Slack as a exception handler
    - Would load Chef::Handler::Slack from /var/chef/handlers/slack_handler_webhook.rb
    ================================================================================
    Error executing action `enable` on resource 'chef_handler[Chef::Handler::Slack]'
    ================================================================================

    NameError
    ---------
    uninitialized constant Slack

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/chef_handler/libraries/helpers.rb:51:in `const_get'
    /var/chef/cache/cookbooks/chef_handler/libraries/helpers.rb:51:in `get_class'
    /var/chef/cache/cookbooks/chef_handler/providers/default.rb:48:in `block in class_from_file'
    /var/chef/cache/cookbooks/slack_handler/recipes/default.rb:58:in `from_file'
    /var/chef/cache/cookbooks/orcasnet/recipes/default.rb:20:in `from_file'
```
### Commentary

I think this is due to the changes introduced in 0b188d727ece2fe437184649b4e1583df04a2b5d, specifically moving [providers/default.rb lines 48 and 49](https://github.com/chef-cookbooks/chef_handler/commit/0b188d727ece2fe437184649b4e1583df04a2b5d#diff-a27dfd053e213b0e3bff4c49b8a9894eR48) out of the `converge_by` block. Prior to this commit the handler class would not be looked up in why-run mode; after this commit the provider attempts to initialize it even though it hasn't been loaded.

**Comment by shortdudey123** [comment]
Same thing for me

chef_handler v1.4.0
CentOS 7.2
Chef: 12.6.0 and 12.14.60

**Comment by lamont-granquist** [comment]
Someone could submit a PR to wrap the code by checking for `Chef::Config[:why_run]` being set, otherwise I wouldn't consider it a bug -- why-run isn't guaranteed to run or be sane under all conditions and is best used on a mostly-converged box to check for changes.

**Comment by lamont-granquist** [comment]
actually i think i'm going to argue that this is the responsibility of the handler to be why-run safe if you want it to be why-run safe -- or for the handler to disable itself in why-run mode if it gets called in why-run mode.  this cookbook simply doesn't know enough about the semantics of what is being done to decide for the handler what to do in the generic case.

**Comment by lamont-granquist** [comment]
yeah we're not going to revert that change.  that change is also why i bumped the cookbook to 2.0.0 since i figured there might be an edge condition like this.  its the responsibility of the handler itself to make sure that it doesn't bomb if its dependencies haven't been loaded due to chef_gem's getting skipped in why-run and to decide for itself if it should no-op itself in why-run mode or not.

**Comment by bleything** [comment]
> that change is also why i bumped the cookbook to 2.0.0 since i figured there might be an edge condition like this.

But... this is in 1.4.0?

Regardless, thanks for the information. Now that I understand what's going awry here a bit better, I think I can work around it.
