### ISSUE TITLE
Deprecated features used

### ISSUE THREAD

**Issue by tiago-cruz-movile** [chef-cookbooks/chef_handler#48]
### Cookbook version
1.3.0

### Chef-client version
12.17.44

### Platform Details
centos 7

### Scenario:
run chef-client

### Steps to Reproduce:
run chef-client

### Expected Result:
no Deprecated features used!

### Actual Result:
```
Deprecated features used!
  method access to node attributes (node.foo.bar) is deprecated and will be removed in Chef 13, please use bracket syntax (node["foo"]["bar"]) at 1 location:
    - /var/chef/cache/cookbooks/chef_handler/attributes/default.rb:23:in `from_file'
```

**Comment by damm** [comment]
Update your chef-handler you are using an old version of the cookbook.

**Comment by tas50** [comment]
@tiago-cruz-movile You're several releases out of date. Can you try using the latest version of the cookbook and opening this back up if it's still an issue
