### ISSUE TITLE
Deprecation warnings about conflicting resource and method name: supports

### ISSUE THREAD

**Issue by PAStheLoD** [chef-cookbooks/chef_handler#49]
### Cookbook version
2.1.0

### Chef-client version
12.19.36

### Platform Details
Linux Ubuntu 16.04

```
  Property `supports` of resource `chef_handler` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. at 1 location:
    - /var/chef/cache/cookbooks/chef_handler/resources/default.rb:31:in `class_from_file'
   See https://docs.chef.io/deprecations_property_name_collision.html for further details.
```

**Comment by cheeseplus** [comment]
We're currently in the process of sweeping all chef-cookbooks for 13 compatibility so this should be resolved fairly soon.

**Comment by tas50** [comment]
This is actually a false warning that was fixed in the Chef 13 codebase. When we start actually testing on Chef 13 this will pass.

https://github.com/chef/chef/blob/master/RELEASE_NOTES.md#removed-supports-api-from-chefresource
