### ISSUE TITLE
Chef 13. Deprecated feature - overwrites an existing method

### ISSUE THREAD

**Issue by jwitrick** [chef-cookbooks/chef_handler#52]
### Cookbook version
2.1.1

### Chef-client version
12.19.33

### Platform Details
CentOS7

### Scenario:
I am using the LWR: 'chef_hander' to add a custom handler to the end of my chef client runs, and while running chef on 12.x I see the following:

       Deprecated features used!
         Property `supports` of resource `chef_handler` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. at 1 location:
           - /tmp/kitchen/cache/cookbooks/chef_handler/resources/default.rb:31:in `class_from_file'

### Steps to Reproduce:
Should be able to reproduce by doing a chef client run when using the LWR.

### Expected Result:
No deprecation warnings/errors.

### Actual Result:
       Deprecated features used!
         Property `supports` of resource `chef_handler` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. at 1 location:
           - /tmp/kitchen/cache/cookbooks/chef_handler/resources/default.rb:31:in `class_from_file'

**Comment by tas50** [comment]
Despite the warning, this is actually fine for Chef 13. We did some refactoring of the supports code in chef-client which cleared it up.
