### ISSUE TITLE
Using arguments according to README fails.

### ISSUE THREAD

**Issue by grimm26** [chef-cookbooks/chef_handler#60]
### Cookbook version
3.0.0

### Chef-client version
12.19.36

### Platform Details
debian/ubuntu

### Scenario:
Using chef_handler resource with arguments to pass ap ath according to your README.  Switching to a custom resource from LWRP seems to have tightened the property checking.
Changing to make the parameter explicitly an array seems to fix:
```
 chef_handler 'Chef::Handler::JsonFile' do
    source 'chef/handler/json_file'
    arguments [path: '/var/chef/reports']
    action :enable
  end
```
Perhaps this is just a documentation issue.

### Steps to Reproduce:
Use chef_handler according to the README"
```
 chef_handler 'Chef::Handler::JsonFile' do
    source 'chef/handler/json_file'
    arguments path: '/var/chef/reports'
    action :enable
  end
```

### Expected Result:
Have it converge.

### Actual Result:
```
....
Chef::Exceptions::ValidationFailed
  ----------------------------------
  Property arguments must be one of: Array, String!  You passed {:path=>"/var/chef/reports"}
....
```

**Comment by tas50** [comment]
This should be fixed in 3.0.1. Thanks for the report
