### ISSUE TITLE
c:\chef\handlers no longer exists

### ISSUE THREAD

**Issue by spuder** [chef-cookbooks/chef_handler#61]
### Cookbook version
3.x

### Chef-client version
12.x.x

### Platform Details
windows

Version 3.x of the cookbook no longer creates c:\chef\handlers on windows systems. This results in bootstrapping errors like: 

```
10.254.59.77 [2017-06-22T18:23:33+00:00] WARN: chef_handler::default recipe has been deprecated. Use the chef_handler resource instead to define handlers from your own wrapper cookbook.
10.254.59.77 [2017-06-22T18:23:33+00:00] INFO: Processing cookbook_file[c:/chef/handlers/slack_handler_webhook.rb] action create (slack_handler::default line 35)
10.254.59.77
10.254.59.77
10.254.59.77 ================================================================================
10.254.59.77 Error executing action `create` on resource 'cookbook_file[c:/chef/handlers/slack_handler_webhook.rb]'
10.254.59.77 ================================================================================
10.254.59.77
10.254.59.77 Chef::Exceptions::EnclosingDirectoryDoesNotExist
10.254.59.77 ------------------------------------------------
10.254.59.77 Parent directory c:/chef/handlers does not exist.
10.254.59.77
10.254.59.77 Cookbook Trace:
10.254.59.77 ---------------
10.254.59.77 c:/chef/cache/cookbooks/slack_handler/recipes/default.rb:40:in `from_file'
10.254.59.77 c:/chef/cache/cookbooks/nd-web/recipes/default.rb:10:in `from_file'
10.254.59.77
10.254.59.77 Resource Declaration:
10.254.59.77 ---------------------
10.254.59.77 # In c:/chef/cache/cookbooks/slack_handler/recipes/default.rb
10.254.59.77
10.254.59.77  35: cookbook_file handler_file do
10.254.59.77  36:   source handler_source
10.254.59.77  37:   mode "0600"
10.254.59.77  38:   action :nothing
10.254.59.77  39: # end
10.254.59.77  40: end.run_action(:create)
10.254.59.77
10.254.59.77 Compiled Resource:
```

### Steps to reproduce

On windows 2012r2 machine, install slack cookbook (I am using a specific commit since the cookbook isn't maintained anymore)

metadata.rb
```
depends          'windows', '~> 1.43.0'
depends          'iis', '~> 4.1.9'
depends          'slack_handler', '~> 0.1.0'
depends          'slack'
```

berksfile
```
source 'https://supermarket.chef.io'

metadata

cookbook 'slack', github: 'risk-io/chef-slack', ref: '54ba8eed80c96cbfbb780d4ac61c7ac5c9cead4a' # https://github.com/risk-io/chef-slack/issues/10

```

The workaround is to pin v2.1.2 in the metadata, or upgrade to the custom resource way of implementing a handler. (Unfortunately not all library cookbooks have implemented that yet)

metadata.rb
```
depends          'windows', '~> 1.43.0'
depends          'iis', '~> 4.1.9'
depends          'slack_handler', '~> 0.1.0'
depends          'slack'
depends          'chef_handler', '~> 2.1.2'
```

**Comment by rgriffith** [comment]
I've been running into this on Amazon Linux as well. Reported an issue on the Slack handler project: rackspace-cookbooks/chef-slack_handler#45

**Comment by rmoriz** [comment]
change https://github.com/chef-cookbooks/chef_handler/commit/898788a17e1a291ce21bd328f30385c9f842ed8f#diff-55bf87238c9b8af164c5133a60721f12 - one can argue if the directory belongs to the installation of a custom handler or just to setup the foundation for custom handlers.

**Comment by tas50** [comment]
I’m adding the Type: Jump In GitHub label to this issue. This is a great issue for someone to get their feet wet with and we’d love a PR to resolves the issue.

**Comment by tas50** [comment]
This is potentially something we want to get added, but since this resource is included in Chef 14 we'll want to get this issue created in the Chef repo itself. If you could copy/paste it there it would be helpful to move things forward from there https://github.com/chef/chef/issues/new
