### ISSUE TITLE
NameError in ChefSpec when switching between SoloRunner and ServerRunner

### ISSUE THREAD

**Issue by ccrebolder** [chef-cookbooks/chef_handler#62]
### Cookbook version
3.0.1

### Chef-client version
```
$ chef --version
Chef Development Kit Version: 1.0.3
chef-client version: 12.16.42
delivery version: master (83358fb62c0f711c70ad5a81030a6cae4017f103)
berks version: 5.2.0
kitchen version: 1.13.2
```

### Platform Details
Ubuntu 14.04 and 16.04

### Scenario:
Use ChefSpec::SoloRunner in some test contexts and ChefSpec::ServerRunner in others in a cookbook that depends on chef_handler 3.0.1.

### Steps to Reproduce:
I created a blank test cookbook at https://github.com/ccrebolder/chef_handler_test. It contains nothing in the default recipe and only depends on chef_handler 3.0.1. Clone this cookbook and run rspec to reproduce. The unit tests are:
```
#
# Cookbook Name:: chef_handler_test
# Spec:: default
#
# Copyright (c) 2017 The Authors, All Rights Reserved.

require 'spec_helper'

describe 'chef_handler_test::default' do
  context 'When using ChefSpec::ServerRunner' do
    let(:server_run) do
      runner = ChefSpec::ServerRunner.new
      runner.converge(described_recipe)
    end

    it 'converges successfully' do
      expect { server_run }.to_not raise_error
    end
  end

  context 'When using ChefSpec::SoloRunner' do
    let(:solo_run) do
      runner = ChefSpec::SoloRunner.new
      runner.converge(described_recipe)
    end

    it 'converges successfully' do
      expect { solo_run }.to_not raise_error
    end
  end
end
```

### Expected Result:
Tests pass.

### Actual Result:
A NameError occurs
```
       expected no Exception, got #<NameError: uninitialized constant Custom resource chef_handler from cookbook chef_handler::Helpers> with backtrace:
         # /tmp/d20170626-10880-vznjpy/cookbooks/chef_handler/resources/default.rb:60:in `block in class_from_file'
         # /tmp/d20170626-10880-vznjpy/cookbooks/chef_handler/resources/default.rb:59:in `class_from_file'
         # ./spec/unit/recipes/default_spec.rb:24:in `block (3 levels) in <top (required)>'
         # ./spec/unit/recipes/default_spec.rb:28:in `block (4 levels) in <top (required)>'
         # ./spec/unit/recipes/default_spec.rb:28:in `block (3 levels) in <top (required)>'
     # ./spec/unit/recipes/default_spec.rb:28:in `block (3 levels) in <top (required)>'
```

I fully realize this is probably a bug in ChefSpec, but when I change https://github.com/chef-cookbooks/chef_handler/blob/master/libraries/helpers.rb#L18 and https://github.com/chef-cookbooks/chef_handler/blob/master/resources/default.rb#L60 to be anything but "ChefHandler", the tests pass. It does not seem to matter whether I do ChefSpec::SoloRunner first or ChefSpec::ServerRunner, the second one always fails. Let me know if I should file this bug in ChefSpec instead, I am only filing here because I have not seen this error before in any other cookbook.

**Comment by rmoriz** [comment]
I can confirm this issue with:

- Chef Development Kit Version: 1.5.0
- chef_handler (3.0.1)

for us, neither SoloRunner nor ServerRunner work.



```
 NameError:
       uninitialized constant Custom resource chef_handler from cookbook chef_handler::Helpers
     # /var/folders/48/v3jpvqg155d2qfktth99_8t40000gp/T/d20170630-70853-1dmejyb/cookbooks/chef_handler/resources/default.rb:60:in `block in class_from_file'
     # /var/folders/48/v3jpvqg155d2qfktth99_8t40000gp/T/d20170630-70853-1dmejyb/cookbooks/chef_handler/resources/default.rb:59:in `class_from_file'
```
